// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package minifier

import (
	"github.com/oleshko-g/url-minifier/internal/transport/http"
	"sync"
)

// Ensure, that ServiceMock does implement http.Service.
// If this is not the case, regenerate this file with moq.
var _ http.Service = &ServiceMock{}

// ServiceMock is a mock implementation of http.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked http.Service
//		mockedService := &ServiceMock{
//			MinifyURLFunc: func(url string) (string, error) {
//				panic("mock out the MinifyURL method")
//			},
//			PingFunc: func() error {
//				panic("mock out the Ping method")
//			},
//			UnMinifyURLFunc: func(id string) (string, error) {
//				panic("mock out the UnMinifyURL method")
//			},
//		}
//
//		// use mockedService in code that requires http.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// MinifyURLFunc mocks the MinifyURL method.
	MinifyURLFunc func(url string) (string, error)

	// PingFunc mocks the Ping method.
	PingFunc func() error

	// UnMinifyURLFunc mocks the UnMinifyURL method.
	UnMinifyURLFunc func(id string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// MinifyURL holds details about calls to the MinifyURL method.
		MinifyURL []struct {
			// URL is the url argument value.
			URL string
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
		}
		// UnMinifyURL holds details about calls to the UnMinifyURL method.
		UnMinifyURL []struct {
			// ID is the id argument value.
			ID string
		}
	}
	lockMinifyURL   sync.RWMutex
	lockPing        sync.RWMutex
	lockUnMinifyURL sync.RWMutex
}

// MinifyURL calls MinifyURLFunc.
func (mock *ServiceMock) MinifyURL(url string) (string, error) {
	if mock.MinifyURLFunc == nil {
		panic("ServiceMock.MinifyURLFunc: method is nil but Service.MinifyURL was just called")
	}
	callInfo := struct {
		URL string
	}{
		URL: url,
	}
	mock.lockMinifyURL.Lock()
	mock.calls.MinifyURL = append(mock.calls.MinifyURL, callInfo)
	mock.lockMinifyURL.Unlock()
	return mock.MinifyURLFunc(url)
}

// MinifyURLCalls gets all the calls that were made to MinifyURL.
// Check the length with:
//
//	len(mockedService.MinifyURLCalls())
func (mock *ServiceMock) MinifyURLCalls() []struct {
	URL string
} {
	var calls []struct {
		URL string
	}
	mock.lockMinifyURL.RLock()
	calls = mock.calls.MinifyURL
	mock.lockMinifyURL.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *ServiceMock) Ping() error {
	if mock.PingFunc == nil {
		panic("ServiceMock.PingFunc: method is nil but Service.Ping was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc()
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedService.PingCalls())
func (mock *ServiceMock) PingCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// UnMinifyURL calls UnMinifyURLFunc.
func (mock *ServiceMock) UnMinifyURL(id string) (string, error) {
	if mock.UnMinifyURLFunc == nil {
		panic("ServiceMock.UnMinifyURLFunc: method is nil but Service.UnMinifyURL was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockUnMinifyURL.Lock()
	mock.calls.UnMinifyURL = append(mock.calls.UnMinifyURL, callInfo)
	mock.lockUnMinifyURL.Unlock()
	return mock.UnMinifyURLFunc(id)
}

// UnMinifyURLCalls gets all the calls that were made to UnMinifyURL.
// Check the length with:
//
//	len(mockedService.UnMinifyURLCalls())
func (mock *ServiceMock) UnMinifyURLCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockUnMinifyURL.RLock()
	calls = mock.calls.UnMinifyURL
	mock.lockUnMinifyURL.RUnlock()
	return calls
}
