// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package minifier

import (
	"context"
	"sync"

	"github.com/oleshko-g/url-minifier/internal/service/minifier"
	"github.com/oleshko-g/url-minifier/internal/transport/http"
)

// Ensure, that ServiceMock does implement http.Service.
// If this is not the case, regenerate this file with moq.
var _ http.Service = &ServiceMock{}

// ServiceMock is a mock implementation of http.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked http.Service
//		mockedService := &ServiceMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			DeleteUserURLsFunc: func(ctx context.Context, userID string, minifiedIDs []string) error {
//				panic("mock out the DeleteUserURLs method")
//			},
//			MinifyURLFunc: func(ctx context.Context, userID string, url string) (string, error) {
//				panic("mock out the MinifyURL method")
//			},
//			MinifyURLsFunc: func(ctx context.Context, userID string, urls []map[string]string) ([]map[string]string, error) {
//				panic("mock out the MinifyURLs method")
//			},
//			PingFunc: func() error {
//				panic("mock out the Ping method")
//			},
//			UnMinifyURLFunc: func(id string) (string, error) {
//				panic("mock out the UnMinifyURL method")
//			},
//			UnMinifyUserURLFunc: func(ctx context.Context, id string) (string, bool, error) {
//				panic("mock out the UnMinifyUserURL method")
//			},
//			UserURLsFunc: func(ctx context.Context, userID string) ([]minifier.URL, error) {
//				panic("mock out the UserURLs method")
//			},
//		}
//
//		// use mockedService in code that requires http.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// DeleteUserURLsFunc mocks the DeleteUserURLs method.
	DeleteUserURLsFunc func(ctx context.Context, userID string, minifiedIDs []string) error

	// MinifyURLFunc mocks the MinifyURL method.
	MinifyURLFunc func(ctx context.Context, userID string, url string) (string, error)

	// MinifyURLsFunc mocks the MinifyURLs method.
	MinifyURLsFunc func(ctx context.Context, userID string, urls []map[string]string) ([]map[string]string, error)

	// PingFunc mocks the Ping method.
	PingFunc func() error

	// UnMinifyURLFunc mocks the UnMinifyURL method.
	UnMinifyURLFunc func(id string) (string, error)

	// UnMinifyUserURLFunc mocks the UnMinifyUserURL method.
	UnMinifyUserURLFunc func(ctx context.Context, id string) (string, bool, error)

	// UserURLsFunc mocks the UserURLs method.
	UserURLsFunc func(ctx context.Context, userID string) ([]minifier.URL, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// DeleteUserURLs holds details about calls to the DeleteUserURLs method.
		DeleteUserURLs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// MinifiedIDs is the minifiedIDs argument value.
			MinifiedIDs []string
		}
		// MinifyURL holds details about calls to the MinifyURL method.
		MinifyURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// URL is the url argument value.
			URL string
		}
		// MinifyURLs holds details about calls to the MinifyURLs method.
		MinifyURLs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Urls is the urls argument value.
			Urls []map[string]string
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
		}
		// UnMinifyURL holds details about calls to the UnMinifyURL method.
		UnMinifyURL []struct {
			// ID is the id argument value.
			ID string
		}
		// UnMinifyUserURL holds details about calls to the UnMinifyUserURL method.
		UnMinifyUserURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// UserURLs holds details about calls to the UserURLs method.
		UserURLs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockClose           sync.RWMutex
	lockDeleteUserURLs  sync.RWMutex
	lockMinifyURL       sync.RWMutex
	lockMinifyURLs      sync.RWMutex
	lockPing            sync.RWMutex
	lockUnMinifyURL     sync.RWMutex
	lockUnMinifyUserURL sync.RWMutex
	lockUserURLs        sync.RWMutex
}

// Close calls CloseFunc.
func (mock *ServiceMock) Close() error {
	if mock.CloseFunc == nil {
		panic("ServiceMock.CloseFunc: method is nil but Service.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedService.CloseCalls())
func (mock *ServiceMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// DeleteUserURLs calls DeleteUserURLsFunc.
func (mock *ServiceMock) DeleteUserURLs(ctx context.Context, userID string, minifiedIDs []string) error {
	if mock.DeleteUserURLsFunc == nil {
		panic("ServiceMock.DeleteUserURLsFunc: method is nil but Service.DeleteUserURLs was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UserID      string
		MinifiedIDs []string
	}{
		Ctx:         ctx,
		UserID:      userID,
		MinifiedIDs: minifiedIDs,
	}
	mock.lockDeleteUserURLs.Lock()
	mock.calls.DeleteUserURLs = append(mock.calls.DeleteUserURLs, callInfo)
	mock.lockDeleteUserURLs.Unlock()
	return mock.DeleteUserURLsFunc(ctx, userID, minifiedIDs)
}

// DeleteUserURLsCalls gets all the calls that were made to DeleteUserURLs.
// Check the length with:
//
//	len(mockedService.DeleteUserURLsCalls())
func (mock *ServiceMock) DeleteUserURLsCalls() []struct {
	Ctx         context.Context
	UserID      string
	MinifiedIDs []string
} {
	var calls []struct {
		Ctx         context.Context
		UserID      string
		MinifiedIDs []string
	}
	mock.lockDeleteUserURLs.RLock()
	calls = mock.calls.DeleteUserURLs
	mock.lockDeleteUserURLs.RUnlock()
	return calls
}

// MinifyURL calls MinifyURLFunc.
func (mock *ServiceMock) MinifyURL(ctx context.Context, userID string, url string) (string, error) {
	if mock.MinifyURLFunc == nil {
		panic("ServiceMock.MinifyURLFunc: method is nil but Service.MinifyURL was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		URL    string
	}{
		Ctx:    ctx,
		UserID: userID,
		URL:    url,
	}
	mock.lockMinifyURL.Lock()
	mock.calls.MinifyURL = append(mock.calls.MinifyURL, callInfo)
	mock.lockMinifyURL.Unlock()
	return mock.MinifyURLFunc(ctx, userID, url)
}

// MinifyURLCalls gets all the calls that were made to MinifyURL.
// Check the length with:
//
//	len(mockedService.MinifyURLCalls())
func (mock *ServiceMock) MinifyURLCalls() []struct {
	Ctx    context.Context
	UserID string
	URL    string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		URL    string
	}
	mock.lockMinifyURL.RLock()
	calls = mock.calls.MinifyURL
	mock.lockMinifyURL.RUnlock()
	return calls
}

// MinifyURLs calls MinifyURLsFunc.
func (mock *ServiceMock) MinifyURLs(ctx context.Context, userID string, urls []map[string]string) ([]map[string]string, error) {
	if mock.MinifyURLsFunc == nil {
		panic("ServiceMock.MinifyURLsFunc: method is nil but Service.MinifyURLs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Urls   []map[string]string
	}{
		Ctx:    ctx,
		UserID: userID,
		Urls:   urls,
	}
	mock.lockMinifyURLs.Lock()
	mock.calls.MinifyURLs = append(mock.calls.MinifyURLs, callInfo)
	mock.lockMinifyURLs.Unlock()
	return mock.MinifyURLsFunc(ctx, userID, urls)
}

// MinifyURLsCalls gets all the calls that were made to MinifyURLs.
// Check the length with:
//
//	len(mockedService.MinifyURLsCalls())
func (mock *ServiceMock) MinifyURLsCalls() []struct {
	Ctx    context.Context
	UserID string
	Urls   []map[string]string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Urls   []map[string]string
	}
	mock.lockMinifyURLs.RLock()
	calls = mock.calls.MinifyURLs
	mock.lockMinifyURLs.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *ServiceMock) Ping() error {
	if mock.PingFunc == nil {
		panic("ServiceMock.PingFunc: method is nil but Service.Ping was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc()
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedService.PingCalls())
func (mock *ServiceMock) PingCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// UnMinifyURL calls UnMinifyURLFunc.
func (mock *ServiceMock) UnMinifyURL(id string) (string, error) {
	if mock.UnMinifyURLFunc == nil {
		panic("ServiceMock.UnMinifyURLFunc: method is nil but Service.UnMinifyURL was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockUnMinifyURL.Lock()
	mock.calls.UnMinifyURL = append(mock.calls.UnMinifyURL, callInfo)
	mock.lockUnMinifyURL.Unlock()
	return mock.UnMinifyURLFunc(id)
}

// UnMinifyURLCalls gets all the calls that were made to UnMinifyURL.
// Check the length with:
//
//	len(mockedService.UnMinifyURLCalls())
func (mock *ServiceMock) UnMinifyURLCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockUnMinifyURL.RLock()
	calls = mock.calls.UnMinifyURL
	mock.lockUnMinifyURL.RUnlock()
	return calls
}

// UnMinifyUserURL calls UnMinifyUserURLFunc.
func (mock *ServiceMock) UnMinifyUserURL(ctx context.Context, id string) (string, bool, error) {
	if mock.UnMinifyUserURLFunc == nil {
		panic("ServiceMock.UnMinifyUserURLFunc: method is nil but Service.UnMinifyUserURL was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockUnMinifyUserURL.Lock()
	mock.calls.UnMinifyUserURL = append(mock.calls.UnMinifyUserURL, callInfo)
	mock.lockUnMinifyUserURL.Unlock()
	return mock.UnMinifyUserURLFunc(ctx, id)
}

// UnMinifyUserURLCalls gets all the calls that were made to UnMinifyUserURL.
// Check the length with:
//
//	len(mockedService.UnMinifyUserURLCalls())
func (mock *ServiceMock) UnMinifyUserURLCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockUnMinifyUserURL.RLock()
	calls = mock.calls.UnMinifyUserURL
	mock.lockUnMinifyUserURL.RUnlock()
	return calls
}

// UserURLs calls UserURLsFunc.
func (mock *ServiceMock) UserURLs(ctx context.Context, userID string) ([]minifier.URL, error) {
	if mock.UserURLsFunc == nil {
		panic("ServiceMock.UserURLsFunc: method is nil but Service.UserURLs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockUserURLs.Lock()
	mock.calls.UserURLs = append(mock.calls.UserURLs, callInfo)
	mock.lockUserURLs.Unlock()
	return mock.UserURLsFunc(ctx, userID)
}

// UserURLsCalls gets all the calls that were made to UserURLs.
// Check the length with:
//
//	len(mockedService.UserURLsCalls())
func (mock *ServiceMock) UserURLsCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockUserURLs.RLock()
	calls = mock.calls.UserURLs
	mock.lockUserURLs.RUnlock()
	return calls
}
