// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package file

import (
	"github.com/oleshko-g/url-minifier/internal/service/minifier"
	"sync"
)

// Ensure, that StoragerMock does implement minifier.Storager.
// If this is not the case, regenerate this file with moq.
var _ minifier.Storager = &StoragerMock{}

// StoragerMock is a mock implementation of minifier.Storager.
//
//	func TestSomethingThatUsesStorager(t *testing.T) {
//
//		// make and configure a mocked minifier.Storager
//		mockedStorager := &StoragerMock{
//			RetrieveFunc: func(key string) (string, error) {
//				panic("mock out the Retrieve method")
//			},
//			SaveFunc: func(key string, value string) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedStorager in code that requires minifier.Storager
//		// and then make assertions.
//
//	}
type StoragerMock struct {
	// RetrieveFunc mocks the Retrieve method.
	RetrieveFunc func(key string) (string, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(key string, value string) error

	// calls tracks calls to the methods.
	calls struct {
		// Retrieve holds details about calls to the Retrieve method.
		Retrieve []struct {
			// Key is the key argument value.
			Key string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
	}
	lockRetrieve sync.RWMutex
	lockSave     sync.RWMutex
}

// Retrieve calls RetrieveFunc.
func (mock *StoragerMock) Retrieve(key string) (string, error) {
	if mock.RetrieveFunc == nil {
		panic("StoragerMock.RetrieveFunc: method is nil but Storager.Retrieve was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockRetrieve.Lock()
	mock.calls.Retrieve = append(mock.calls.Retrieve, callInfo)
	mock.lockRetrieve.Unlock()
	return mock.RetrieveFunc(key)
}

// RetrieveCalls gets all the calls that were made to Retrieve.
// Check the length with:
//
//	len(mockedStorager.RetrieveCalls())
func (mock *StoragerMock) RetrieveCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockRetrieve.RLock()
	calls = mock.calls.Retrieve
	mock.lockRetrieve.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *StoragerMock) Save(key string, value string) error {
	if mock.SaveFunc == nil {
		panic("StoragerMock.SaveFunc: method is nil but Storager.Save was just called")
	}
	callInfo := struct {
		Key   string
		Value string
	}{
		Key:   key,
		Value: value,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(key, value)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedStorager.SaveCalls())
func (mock *StoragerMock) SaveCalls() []struct {
	Key   string
	Value string
} {
	var calls []struct {
		Key   string
		Value string
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
