// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockStorage

import (
	"context"
	"github.com/oleshko-g/url-minifier/internal/storage"
	"sync"
)

// Ensure, that StoragerMock does implement storage.Storager.
// If this is not the case, regenerate this file with moq.
var _ storage.Storager = &StoragerMock{}

// StoragerMock is a mock implementation of storage.Storager.
//
//	func TestSomethingThatUsesStorager(t *testing.T) {
//
//		// make and configure a mocked storage.Storager
//		mockedStorager := &StoragerMock{
//			PingFunc: func() error {
//				panic("mock out the Ping method")
//			},
//			RetrieveFunc: func(key string) (string, error) {
//				panic("mock out the Retrieve method")
//			},
//			SaveFunc: func(key string, value string) error {
//				panic("mock out the Save method")
//			},
//			SaveListFunc: func(values []map[string]string) error {
//				panic("mock out the SaveList method")
//			},
//			SaveUserStringFunc: func(ctx context.Context, user_id string, key string, value string) error {
//				panic("mock out the SaveUserString method")
//			},
//		}
//
//		// use mockedStorager in code that requires storage.Storager
//		// and then make assertions.
//
//	}
type StoragerMock struct {
	// PingFunc mocks the Ping method.
	PingFunc func() error

	// RetrieveFunc mocks the Retrieve method.
	RetrieveFunc func(key string) (string, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(key string, value string) error

	// SaveListFunc mocks the SaveList method.
	SaveListFunc func(values []map[string]string) error

	// SaveUserStringFunc mocks the SaveUserString method.
	SaveUserStringFunc func(ctx context.Context, user_id string, key string, value string) error

	// calls tracks calls to the methods.
	calls struct {
		// Ping holds details about calls to the Ping method.
		Ping []struct {
		}
		// Retrieve holds details about calls to the Retrieve method.
		Retrieve []struct {
			// Key is the key argument value.
			Key string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
		// SaveList holds details about calls to the SaveList method.
		SaveList []struct {
			// Values is the values argument value.
			Values []map[string]string
		}
		// SaveUserString holds details about calls to the SaveUserString method.
		SaveUserString []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User_id is the user_id argument value.
			User_id string
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
	}
	lockPing           sync.RWMutex
	lockRetrieve       sync.RWMutex
	lockSave           sync.RWMutex
	lockSaveList       sync.RWMutex
	lockSaveUserString sync.RWMutex
}

// Ping calls PingFunc.
func (mock *StoragerMock) Ping() error {
	if mock.PingFunc == nil {
		panic("StoragerMock.PingFunc: method is nil but Storager.Ping was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc()
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedStorager.PingCalls())
func (mock *StoragerMock) PingCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Retrieve calls RetrieveFunc.
func (mock *StoragerMock) Retrieve(key string) (string, error) {
	if mock.RetrieveFunc == nil {
		panic("StoragerMock.RetrieveFunc: method is nil but Storager.Retrieve was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockRetrieve.Lock()
	mock.calls.Retrieve = append(mock.calls.Retrieve, callInfo)
	mock.lockRetrieve.Unlock()
	return mock.RetrieveFunc(key)
}

// RetrieveCalls gets all the calls that were made to Retrieve.
// Check the length with:
//
//	len(mockedStorager.RetrieveCalls())
func (mock *StoragerMock) RetrieveCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockRetrieve.RLock()
	calls = mock.calls.Retrieve
	mock.lockRetrieve.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *StoragerMock) Save(key string, value string) error {
	if mock.SaveFunc == nil {
		panic("StoragerMock.SaveFunc: method is nil but Storager.Save was just called")
	}
	callInfo := struct {
		Key   string
		Value string
	}{
		Key:   key,
		Value: value,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(key, value)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedStorager.SaveCalls())
func (mock *StoragerMock) SaveCalls() []struct {
	Key   string
	Value string
} {
	var calls []struct {
		Key   string
		Value string
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// SaveList calls SaveListFunc.
func (mock *StoragerMock) SaveList(values []map[string]string) error {
	if mock.SaveListFunc == nil {
		panic("StoragerMock.SaveListFunc: method is nil but Storager.SaveList was just called")
	}
	callInfo := struct {
		Values []map[string]string
	}{
		Values: values,
	}
	mock.lockSaveList.Lock()
	mock.calls.SaveList = append(mock.calls.SaveList, callInfo)
	mock.lockSaveList.Unlock()
	return mock.SaveListFunc(values)
}

// SaveListCalls gets all the calls that were made to SaveList.
// Check the length with:
//
//	len(mockedStorager.SaveListCalls())
func (mock *StoragerMock) SaveListCalls() []struct {
	Values []map[string]string
} {
	var calls []struct {
		Values []map[string]string
	}
	mock.lockSaveList.RLock()
	calls = mock.calls.SaveList
	mock.lockSaveList.RUnlock()
	return calls
}

// SaveUserString calls SaveUserStringFunc.
func (mock *StoragerMock) SaveUserString(ctx context.Context, user_id string, key string, value string) error {
	if mock.SaveUserStringFunc == nil {
		panic("StoragerMock.SaveUserStringFunc: method is nil but Storager.SaveUserString was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		User_id string
		Key     string
		Value   string
	}{
		Ctx:     ctx,
		User_id: user_id,
		Key:     key,
		Value:   value,
	}
	mock.lockSaveUserString.Lock()
	mock.calls.SaveUserString = append(mock.calls.SaveUserString, callInfo)
	mock.lockSaveUserString.Unlock()
	return mock.SaveUserStringFunc(ctx, user_id, key, value)
}

// SaveUserStringCalls gets all the calls that were made to SaveUserString.
// Check the length with:
//
//	len(mockedStorager.SaveUserStringCalls())
func (mock *StoragerMock) SaveUserStringCalls() []struct {
	Ctx     context.Context
	User_id string
	Key     string
	Value   string
} {
	var calls []struct {
		Ctx     context.Context
		User_id string
		Key     string
		Value   string
	}
	mock.lockSaveUserString.RLock()
	calls = mock.calls.SaveUserString
	mock.lockSaveUserString.RUnlock()
	return calls
}
