package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/types"
	"io"
	"log"
	"os"
	"path"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

func main() {
	// dirPath := os.Args[:1]
	dirPath := "../../"

	pkgs, err := loadPackages(dirPath)
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		err = generateResetMethods(pkg)
		if err != nil {
			log.Fatal(err)
		}
	}
}

func loadPackages(dirPath string) ([]*packages.Package, error) {
	pkgs, err := packages.Load(&packages.Config{
		Dir:  dirPath,
		Mode: packages.LoadSyntax,
	}, "./...")
	if err != nil {
		return nil, err
	}

	return pkgs, nil
}

func generateResetMethods(pkg *packages.Package) error {
	for _, file := range pkg.Syntax {
		structTypesToReset := structTypesToReset(file)

		for name, structToReset := range structTypesToReset {
			b := bytes.Buffer{}

			pkgName := pkg.Name
			fmt.Printf("generating \"reset.get.go\" for pakage: %s", pkgName)
			templ, err := template.New("pkg").Parse(pkgTmpl)
			if err != nil {
				return err
			}

			err = templ.Execute(&b, pkg.Name)
			if err != nil {
				return err
			}

			err = generateResetMethod(&b, name, structToReset.Fields.List)
			if err != nil {
				return err
			}

			path := path.Join(pkg.Dir, "reset.gen.go")

			err = os.WriteFile(path, b.Bytes(), 0o755)
			if err != nil {
				return err
			}
		}

	}

	return nil
}

func generateResetMethod(wr io.Writer, name string, fields []*ast.Field) error {
	templ, err := template.New("resetMeth").Parse(resetMethTmpl)
	if err != nil {
		return err
	}

	resetMeth := struct {
		RecName    string
		StructName string
	}{
		RecName:    strings.ToLower(name[:1]),
		StructName: name,
	}

	err = templ.Execute(wr, resetMeth)
	if err != nil {
		return err
	}

	_, _ = wr, fields
	return nil
}

// structTypesToReset returns struct types marked with `// generate:reset` comment.
func structTypesToReset(file *ast.File) map[string]*ast.StructType {
	structTypes := make(map[string]*ast.StructType)

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if ok {
			if hasComment("// generate:reset", genDecl) {
				if name, structType := isStructDecl(genDecl); structType != nil {
					structTypes[name] = structType
				}
			}
		}
	}

	return structTypes
}

// resetStructs return a [ResetStruct] slice to feed into a template to generate the Reset method
func resetStructs(structTypes map[string]*ast.StructType) []ResetStruct {
	var resetStructs []ResetStruct

	for name, structType := range structTypes {

		resetStructs = append(resetStructs, ResetStruct{
			Name:             name,
			FieldsByResetWay: fieldsByResetWay(structType.Fields),
		})
	}

	return resetStructs
}

func fieldsByResetWay(fields *ast.FieldList) map[way][]string {
	fieldsByResetWay := make(map[way][]string)

	for _, field := range fields.List {
		// * TODO: lookup in types info and determine the basic type and

		if fieldType, ok := field.Type.(types.Type); ok {
			underlyingType := underlyingTypeOf(fieldType)

			if basicType := isBasicType(underlyingType); basicType != nil {
				if isScalar(basicType.Kind()) {
					fmt.Println(field.Type.(*ast.Ident).Name)
				}
			}
			_ = underlyingType

		}

		fieldTypeName := field.Type.(*ast.Ident).Name
		// * TODO: determine the reset way
		resetWay := resetWay(fieldTypeName)

		var fieldNames []string
		for _, fieldIdent := range field.Names {
			fieldNames = append(fieldNames, fieldIdent.Name)
		}

		fieldsByResetWay[resetWay] = append(fieldsByResetWay[resetWay], fieldNames...)
	}
	return fieldsByResetWay
}

func underlyingTypeOf(t types.Type) types.Type {
	var underlying types.Type
	for {
		underlying = t.Underlying()
		if underlying == t {
			return underlying
		}
	}
}

func isScalar(t types.BasicKind) bool {

	if t != types.UnsafePointer &&
		t != types.UntypedNil &&
		t != types.Rune &&
		t != types.Byte {
		return true
	}

	return false
}

func resetWay(fieldTypeName string) way {

	switch fieldTypeName {
	default:
		return ""
	}

}

func isBasicType(t types.Type) *types.Basic {
	if v, ok := t.(*types.Basic); ok {
		return v
	}
	return nil
}

func isStructDecl(decl *ast.GenDecl) (name string, typ *ast.StructType) {
	if len(decl.Specs) == 1 {
		if typeSpec, ok := decl.Specs[0].(*ast.TypeSpec); ok {
			if structType, ok := typeSpec.Type.(*ast.StructType); ok {
				return typeSpec.Name.Name, structType
			}
		}
	}

	return "", nil
}

func hasComment(comment string, decl *ast.GenDecl) bool {
	if decl.Doc != nil {
		for _, doc := range decl.Doc.List {
			if doc.Text == comment {
				return true
			}
		}
	}

	return false
}

type ResetStruct struct {
	Name             string
	FieldsByResetWay map[way][]string
}

type way string

func group[E any, K comparable, V any](slice []E, f func(E) (k K, vv []V)) map[K][]V {

	var m = make(map[K][]V)

	for _, v := range slice {
		if k, vv := f(v); vv != nil {
			m[k] = append(m[k], vv...)
		}
	}

	return m
}

var (
	pkgTmpl = `// Code generated by go generate; DO NOT EDIT.
// generated by /cmd/reset

package {{.}}

type Resetter interface {
	Reset()
}

type scalar interface {
	~bool | ~string | ~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr | ~float32 | ~float64 | ~complex64 | ~complex128
}

type zeroer[T scalar] struct{}

func (z zeroer[T]) zero() T {
	var v T
	return v
}

func truncate[T any](v []T) []T {
	return v[:0]
}

`

	resetMethTmpl = `func ({{.RecName}} *{{.StructName}}) Reset() {
	if {{.RecName}} == nil {
		return
	}

}`
)
