// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/api/v1/api.proto

package url_minifier_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MinifyURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinifyURLRequest) Reset() {
	*x = MinifyURLRequest{}
	mi := &file_proto_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinifyURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinifyURLRequest) ProtoMessage() {}

func (x *MinifyURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinifyURLRequest.ProtoReflect.Descriptor instead.
func (*MinifyURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *MinifyURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MinifyURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinifyURLResponse) Reset() {
	*x = MinifyURLResponse{}
	mi := &file_proto_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinifyURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinifyURLResponse) ProtoMessage() {}

func (x *MinifyURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinifyURLResponse.ProtoReflect.Descriptor instead.
func (*MinifyURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *MinifyURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UnminifyURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnminifyURLRequest) Reset() {
	*x = UnminifyURLRequest{}
	mi := &file_proto_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnminifyURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnminifyURLRequest) ProtoMessage() {}

func (x *UnminifyURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnminifyURLRequest.ProtoReflect.Descriptor instead.
func (*UnminifyURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *UnminifyURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnminifyURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnminifyURLResponse) Reset() {
	*x = UnminifyURLResponse{}
	mi := &file_proto_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnminifyURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnminifyURLResponse) ProtoMessage() {}

func (x *UnminifyURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnminifyURLResponse.ProtoReflect.Descriptor instead.
func (*UnminifyURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *UnminifyURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           []*URLData             `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_proto_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsResponse.ProtoReflect.Descriptor instead.
func (*UserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *UserURLsResponse) GetUrl() []*URLData {
	if x != nil {
		return x.Url
	}
	return nil
}

type URLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLData) Reset() {
	*x = URLData{}
	mi := &file_proto_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLData.ProtoReflect.Descriptor instead.
func (*URLData) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *URLData) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLData) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_proto_api_v1_api_proto protoreflect.FileDescriptor

const file_proto_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x16proto/api/v1/api.proto\x12\x0fminifier.api.v1\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\x10MinifyURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"+\n" +
	"\x11MinifyURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"$\n" +
	"\x12UnminifyURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x13UnminifyURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\">\n" +
	"\x10UserURLsResponse\x12*\n" +
	"\x03url\x18\x01 \x03(\v2\x18.minifier.api.v1.URLDataR\x03url\"I\n" +
	"\aURLData\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl2\x8a\x02\n" +
	"\x0fMinifierService\x12R\n" +
	"\tMinifyURL\x12!.minifier.api.v1.MinifyURLRequest\x1a\".minifier.api.v1.MinifyURLResponse\x12X\n" +
	"\vUnminifyURL\x12#.minifier.api.v1.UnminifyURLRequest\x1a$.minifier.api.v1.UnminifyURLResponse\x12I\n" +
	"\fListUserURLs\x12\x16.google.protobuf.Empty\x1a!.minifier.api.v1.UserURLsResponseB@Z>github.com/oleshko-g/url-minifier/proto/api/v1;url_minifier_v1b\x06proto3"

var (
	file_proto_api_v1_api_proto_rawDescOnce sync.Once
	file_proto_api_v1_api_proto_rawDescData []byte
)

func file_proto_api_v1_api_proto_rawDescGZIP() []byte {
	file_proto_api_v1_api_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_api_proto_rawDesc), len(file_proto_api_v1_api_proto_rawDesc)))
	})
	return file_proto_api_v1_api_proto_rawDescData
}

var file_proto_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_api_v1_api_proto_goTypes = []any{
	(*MinifyURLRequest)(nil),    // 0: minifier.api.v1.MinifyURLRequest
	(*MinifyURLResponse)(nil),   // 1: minifier.api.v1.MinifyURLResponse
	(*UnminifyURLRequest)(nil),  // 2: minifier.api.v1.UnminifyURLRequest
	(*UnminifyURLResponse)(nil), // 3: minifier.api.v1.UnminifyURLResponse
	(*UserURLsResponse)(nil),    // 4: minifier.api.v1.UserURLsResponse
	(*URLData)(nil),             // 5: minifier.api.v1.URLData
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_proto_api_v1_api_proto_depIdxs = []int32{
	5, // 0: minifier.api.v1.UserURLsResponse.url:type_name -> minifier.api.v1.URLData
	0, // 1: minifier.api.v1.MinifierService.MinifyURL:input_type -> minifier.api.v1.MinifyURLRequest
	2, // 2: minifier.api.v1.MinifierService.UnminifyURL:input_type -> minifier.api.v1.UnminifyURLRequest
	6, // 3: minifier.api.v1.MinifierService.ListUserURLs:input_type -> google.protobuf.Empty
	1, // 4: minifier.api.v1.MinifierService.MinifyURL:output_type -> minifier.api.v1.MinifyURLResponse
	3, // 5: minifier.api.v1.MinifierService.UnminifyURL:output_type -> minifier.api.v1.UnminifyURLResponse
	4, // 6: minifier.api.v1.MinifierService.ListUserURLs:output_type -> minifier.api.v1.UserURLsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_api_v1_api_proto_init() }
func file_proto_api_v1_api_proto_init() {
	if File_proto_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_api_proto_rawDesc), len(file_proto_api_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_api_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_api_proto_depIdxs,
		MessageInfos:      file_proto_api_v1_api_proto_msgTypes,
	}.Build()
	File_proto_api_v1_api_proto = out.File
	file_proto_api_v1_api_proto_goTypes = nil
	file_proto_api_v1_api_proto_depIdxs = nil
}
