// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/api/v1/api.proto

package url_minifier_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinifierService_MinifyURL_FullMethodName    = "/minifier.api.v1.MinifierService/MinifyURL"
	MinifierService_UnminifyURL_FullMethodName  = "/minifier.api.v1.MinifierService/UnminifyURL"
	MinifierService_ListUserURLs_FullMethodName = "/minifier.api.v1.MinifierService/ListUserURLs"
)

// MinifierServiceClient is the client API for MinifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinifierServiceClient interface {
	MinifyURL(ctx context.Context, in *MinifyURLRequest, opts ...grpc.CallOption) (*MinifyURLResponse, error)
	UnminifyURL(ctx context.Context, in *UnminifyURLRequest, opts ...grpc.CallOption) (*UnminifyURLResponse, error)
	ListUserURLs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserURLsResponse, error)
}

type minifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMinifierServiceClient(cc grpc.ClientConnInterface) MinifierServiceClient {
	return &minifierServiceClient{cc}
}

func (c *minifierServiceClient) MinifyURL(ctx context.Context, in *MinifyURLRequest, opts ...grpc.CallOption) (*MinifyURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MinifyURLResponse)
	err := c.cc.Invoke(ctx, MinifierService_MinifyURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minifierServiceClient) UnminifyURL(ctx context.Context, in *UnminifyURLRequest, opts ...grpc.CallOption) (*UnminifyURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnminifyURLResponse)
	err := c.cc.Invoke(ctx, MinifierService_UnminifyURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minifierServiceClient) ListUserURLs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserURLsResponse)
	err := c.cc.Invoke(ctx, MinifierService_ListUserURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinifierServiceServer is the server API for MinifierService service.
// All implementations must embed UnimplementedMinifierServiceServer
// for forward compatibility.
type MinifierServiceServer interface {
	MinifyURL(context.Context, *MinifyURLRequest) (*MinifyURLResponse, error)
	UnminifyURL(context.Context, *UnminifyURLRequest) (*UnminifyURLResponse, error)
	ListUserURLs(context.Context, *emptypb.Empty) (*UserURLsResponse, error)
	mustEmbedUnimplementedMinifierServiceServer()
}

// UnimplementedMinifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinifierServiceServer struct{}

func (UnimplementedMinifierServiceServer) MinifyURL(context.Context, *MinifyURLRequest) (*MinifyURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MinifyURL not implemented")
}
func (UnimplementedMinifierServiceServer) UnminifyURL(context.Context, *UnminifyURLRequest) (*UnminifyURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnminifyURL not implemented")
}
func (UnimplementedMinifierServiceServer) ListUserURLs(context.Context, *emptypb.Empty) (*UserURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserURLs not implemented")
}
func (UnimplementedMinifierServiceServer) mustEmbedUnimplementedMinifierServiceServer() {}
func (UnimplementedMinifierServiceServer) testEmbeddedByValue()                         {}

// UnsafeMinifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinifierServiceServer will
// result in compilation errors.
type UnsafeMinifierServiceServer interface {
	mustEmbedUnimplementedMinifierServiceServer()
}

func RegisterMinifierServiceServer(s grpc.ServiceRegistrar, srv MinifierServiceServer) {
	// If the following call panics, it indicates UnimplementedMinifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinifierService_ServiceDesc, srv)
}

func _MinifierService_MinifyURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinifyURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinifierServiceServer).MinifyURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinifierService_MinifyURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinifierServiceServer).MinifyURL(ctx, req.(*MinifyURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinifierService_UnminifyURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnminifyURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinifierServiceServer).UnminifyURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinifierService_UnminifyURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinifierServiceServer).UnminifyURL(ctx, req.(*UnminifyURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinifierService_ListUserURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinifierServiceServer).ListUserURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinifierService_ListUserURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinifierServiceServer).ListUserURLs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MinifierService_ServiceDesc is the grpc.ServiceDesc for MinifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minifier.api.v1.MinifierService",
	HandlerType: (*MinifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MinifyURL",
			Handler:    _MinifierService_MinifyURL_Handler,
		},
		{
			MethodName: "UnminifyURL",
			Handler:    _MinifierService_UnminifyURL_Handler,
		},
		{
			MethodName: "ListUserURLs",
			Handler:    _MinifierService_ListUserURLs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/v1/api.proto",
}
