// Code generated by go generate; DO NOT EDIT.
// generated by /cmd/reset

package example

type Resetter interface {
	Reset()
}

type scalar interface {
	~bool | ~string | ~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr | ~float32 | ~float64 | ~complex64 | ~complex128
}

func zero[S scalar]() S {
	var v S
	return v
}

func truncate[T any](v []T) []T {
	return v[:0]
}

// Reset sets the genStruct
func (g *genStruct) Reset() {
	if g == nil {
		return
	}

	clear(g.m)

	g.s = zero[string]()
	g.i = zero[int]()
	g.mb = zero[myBool]()

	*g.sp = zero[string]()

	g.sf = truncate(g.sf)

	if resetter, ok := any(g.st).(Resetter); ok {
		resetter.Reset()
	}

	if resetter, ok := any(g.st2).(Resetter); ok {
		resetter.Reset()
	}

}
